### REGISTER
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "user2",
  "email": "user3@gmail.com",
  "password": "123456",
  "role": "user"
}

### LOGIN
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "password": "123456"
}

### GET CURRENT USER
GET http://localhost:3001/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzJlYTZiZDkzMmI4ZGZhNzAwZDU1NiIsImlhdCI6MTc2NDk0NDU2MSwiZXhwIjoxNzY0OTQ1NDYxfQ.vZKTMmP8M9PeIRPcx8Qhnt5qEO9RP7w-2RDwVp49gqw

### REFRESH TOKEN
POST http://localhost:3001/api/auth/refresh-token

### LOGOUT
POST http://localhost:3001/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzJlYTZiZDkzMmI4ZGZhNzAwZDU1NiIsImlhdCI6MTc2NDk0NDU3NCwiZXhwIjoxNzY0OTQ1NDc0fQ.Xtip3c_He6CHBnYJtKXM6TxvNod4vUUkK8KFrFsOJ7U
